services:
  - type: web
    name: sighttech-backend
    env: python
    buildCommand: chmod +x install_dependencies.sh && ./install_dependencies.sh
    startCommand: cd backend && python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000

  - type: web
    name: sighttech-frontend
    env: static
    buildCommand: echo "Frontend build complete"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /api/*
        destination: https://sighttech-backend.onrender.com/api/* 